#! /bin/bash

if [[ $# == 0 ]]; then
    echo "Syntax: zipencrypt [file]"
    echo "Note that it would generate a file ended in .zip"
    exit
fi

case "$1" in
*.zip)
    zip "$1.zip"      -r -6 --encrypt "$1"
    ;;
*.*)
    zip "${1%.*}.zip" -r -6 --encrypt "$1"
    ;;
*)
    zip "$1.zip"      -r -6 --encrypt "$1"
    ;;
esac
