#! /bin/bash
#
# Written by davidhcefx, 2019.11.7.
# Format of $cmdlist:
#   SPACE SPACE KEY TAB (TAB)* COMMAND

cmdlist=~/.cmdlist
exe=/tmp/cmdtool.exe

help() {
    if ! [ -e $cmdlist ]; then
        echo "  edit		nano $cmdlist" > $cmdlist
    fi
    echo "A tool for commandline shortcuts. Syntax: $(basename $0) [option]"
    echo "Options:"
    cat $cmdlist
    echo ""
}


if [ $# == 0 ]; then
    help
    exit
fi

key=$1; shift
cmd=$(cat $cmdlist | sed -n "/^\ \ $key\t/{s/^\ \ $key//p}" | head -n 1)

if [ "$cmd" == "" ]; then
    echo "Command not found!"
    help
else
    echo "$cmd" > $exe
    bash $exe "$@"
fi
